print('Hello World')
print('What\'s you name?')
my_name=input('>')
print('It\'s good to meet you')
print('The length of your name is : ')
print(len(my_name))
print('What is you age?')
my_age = input('>')
print('You will be '+str(int(my_age)+1)+' in a year')
print(str(int(5.5)))